development:
  adapter: postgresql
  encoding: unicode
  database: TravelAgency_development
  pool: 5
  username: TravelAgency
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: TravelAgency_test
  pool: 5
  username: TravelAgency
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: TravelAgency_production
  pool: 5
  username: TravelAgency
  password:
