TravelAgency::Application.routes.draw do
  root 'pages#home'
  get '/', to: 'pages#home', as: 'home'
  get '/travels/hawaii', to: 'travels#hawaii', as: 'hawaii'
  get '/travels/italy', to: 'travels#italy', as: 'italy'
  get '/travels/china', to: 'travels#china', as: 'china'
  get '/travels/random', to: 'travels#random', as: 'random'
  get '/about', to: 'pages#about', as: 'about'
  get '/contact', to: 'pages#contact', as: 'contact'
  post '/contact', to: 'pages#create', as: 'send'
  get '/favorites' => 'favorites#index', as: 'favorites'
  post '/favorites' => 'favorites#create'
  post '/clearall' => 'favorites#clear_all', as: 'delete_all'
  delete '/favorites/:package_id' => 'favorites#destroy'
end
